### ISSUE TITLE
Missing Textures on release version of mc 1.12.2

### ISSUE THREAD

**Issue by knoxhack** [X-Niter/DTM-Integrations#1]
Maybe you guys can put up a fix for the missing textures, I reported them to the main mod already but haven't had any reply yet 

https://www.curseforge.com/minecraft/mc-mods/days-to-mine/issues/20

![2022-08-02_20 40 30](https://user-images.githubusercontent.com/9358725/182880959-6319bccc-5368-4fd2-a36e-31fa260933bb.png)

**Comment by X-Niter** [comment]
Thanks for letting me know, I've been working on this for the next update.
