### ISSUE TITLE
Airdrops feature request

### ISSUE THREAD

**Issue by knoxhack** [X-Niter/DTM-Integrations#11]
- airdrops to show the dimension they spawned or
- airdrops only send a msg to players in the same dimension they spawned in

**Comment by X-Niter** [comment]
@knoxhack Check out [This Commit that adds the feature](https://github.com/X-Niter/DTM-Integrations/blob/1e9763084b3349bbdad8b9d179440642e85559bb/src/main/java/github/xniter/dtmintegrations/mixin/sevendaystomine/events/MixinTickHandler.java#L83)

And the config for it is [Here](https://github.com/X-Niter/DTM-Integrations/blob/1e9763084b3349bbdad8b9d179440642e85559bb/src/main/java/github/xniter/dtmintegrations/handlers/config/ConfigHandler.java#L163)
And also [Here](https://github.com/X-Niter/DTM-Integrations/blob/1e9763084b3349bbdad8b9d179440642e85559bb/src/main/java/github/xniter/dtmintegrations/handlers/config/ConfigHandler.java#L164)

This not only is updated to show the world name that it is in, but it also adds configuration to use exact location of where it was dropped or you can configure it to use a set "Ranged" location so people have to look for it along with glowing options.

**Comment by knoxhack** [comment]
> 

Awesome 👌
