### ISSUE TITLE
Suggest: Add "SimpleDifficulty"

### ISSUE THREAD

**Issue by dazadazu** [X-Niter/DTM-Integrations#14]
Its a more refined tough as nails mod for 1.12.

**Comment by X-Niter** [comment]
@dazadazu I was already planning to add this as I knew SD existed. I highly appreciate you for opening this up and putting it on my tracker! You are an amazing person! 

Hope to get this out soon soon! 

Also keep in mind, that the integration that I do is simply convert all of 7DTM thirst and stamina into each mod, such as TAN or SD

So if there was something more then that, please don't hesistate to educate me on that as I very well do not know how every mod operates in game :)

Cheers!

**Comment by X-Niter** [comment]
See [DTMIntegrations-1.12.2-1.4.0](https://github.com/X-Niter/DTM-Integrations/releases/tag/1.4.0)
