### ISSUE TITLE
Add custom generic hordes config

### ISSUE THREAD

**Issue by knoxhack** [X-Niter/DTM-Integrations#17]
Add custom generic hordes config to configure the regular hordes

**Comment by X-Niter** [comment]
> Add custom generic hordes config to configure the regular hordes

Do those exist? I've never seen it fired naturally without commands.

**Comment by knoxhack** [comment]
Yes, they do. They are the same as wolf hordes but they are called generic hordes in the config

**Comment by knoxhack** [comment]
I remember using them at some point

**Comment by X-Niter** [comment]
Yeah I looked and saw, it,, I'm trying to see if there is even a natrual event for it though other then running a command to start it.

**Comment by X-Niter** [comment]
I got the config, and option for it done already in 60 seconds, but now I am left at digging for a way to check for that event.

**Comment by X-Niter** [comment]
@knoxhack 
Sent you the jar file on Discord, I'll go from there on tackling this Generic horde event.
It should work without issues though.
