### ISSUE TITLE
torches dont drop anything when broken

### ISSUE THREAD

**Issue by knoxhack** [X-Niter/DTM-Integrations#24]
current config:
    # Can Seven Days To Mine change torches? [Set to False if any other mods installed already make modifications to vanilla torches] [default: true]
    B:"Change Torches"=false
    
    DTMI version:
    1.5.0

**Comment by knoxhack** [comment]
this was probably related to this
https://github.com/NFINIT-Development/Planetary/issues/59

**Comment by X-Niter** [comment]
> this was probably related to this [NFINIT-Development/Planetary#59](https://github.com/NFINIT-Development/Planetary/issues/59)

That looks about right, as I tested my end of 7DTMI and this issue did not present it self
