### ISSUE TITLE
airdrops text chat problem

### ISSUE THREAD

**Issue by knoxhack** [X-Niter/DTM-Integrations#25]
"Airdrops are wierd one the z cords are not showing and 2 even tho tons spawn their not like near the location where I used the /airdrop command" Planetary player

[https://cdn.discordapp.com/attachments/670616371926663192/1016208490009735278/IMG_20220905_004928_HDR.jpg](https://cdn.discordapp.com/attachments/670616371926663192/1016208490009735278/IMG_20220905_004928_HDR.jpg)

**Comment by X-Niter** [comment]
Did you change anything about the Airdrops messages? And if so exactly what did you change?

**Comment by X-Niter** [comment]
Doing `/airdrop` without giving specific X, Y, Z coordinates will use the designed system of randomly getting a spot, the more players on, the more spots it can be spawned at by random.

Give it X, Y, Z and you will have it with in the location you set it to, and you can technically stay still at that point.

There is only one real limitation to the airdrops, sometimes, when you give it the exact coordinates, it will drop around the coordinates, and then once it get's down to the ground it might look to "teleport" to the X and Z you gave it, this is a client/server desync that I was working to try and fix, I had to get some help with this, and even though we made it better, it is not perfect as I wish it was.
