### ISSUE TITLE
Normal Bandage does not heal

### ISSUE THREAD

**Issue by aebischer** [X-Niter/DTM-Integrations#5]
bandage(7days mod) and plaster(rough mod) not heal when use.
i found no way to heal when wounded.

**Comment by X-Niter** [comment]
@aebischer This is the DTMI mod issues not EOL. 

For EOL, I tested plaster single player and multiplayer, and it does heal.

The advanced bandage from 7 Days to mine does apply a healing affect, but you're correct about the regular 7 days to mine bandage, it does not heal and I'll look into this.
