### ISSUE TITLE
GregTech weapons & transutation table

### ISSUE THREAD

**Issue by aebischer** [X-Niter/DTM-Integrations#8]
I put a axe, a sword and a shovel level2 (material damascus)  from gregtech in my transutation table
and they registered as level6 (material neutronium)

**Comment by X-Niter** [comment]
Hey @aebischer , this one is also a EOL specific one mate :) 

I only ask you to move that way I know where the issue is, when the issue is here under the DTMI mod, I keep thinking it's actually an issue with this mod when this issue is actually an issue with Project E and GregTech.

**Comment by X-Niter** [comment]
Moved to https://github.com/X-Niter/eol-tbd/issues/10
